### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by digitalrub** [senlin/so-related-posts#3]
![screen shot 2015-05-07 at 8 41 35 am](https://cloud.githubusercontent.com/assets/12296622/7516440/ef2d6aa4-f494-11e4-94dd-45d8da0b953c.png)

When I tick the box, no post list shows up. I would guess a JS conflict but I'm not getting any errors either. My enabled plugins:

Co-Authors Plus
Contact Form 7
Easy Author Image
Meta Box
PullQuote
Really Simple CAPTCHA
SO Related Posts
Subtitles
Top 10

I tried disabling them all and still nothing. I'm using a child theme of twentythirteen and the latest version of WP (4.2)

**Comment by senlin** [comment]
Thank you very much for reporting this!

It turns out that there is something in the latest release of the Meta Box plugin (version 4.5.1) that is triggering this. We're not sure yet what it is and will contact Rilwis, the developer of the Meta Box plugin to see if he can assist.

In the meantime, you can use [Meta Box 4.5](https://wordpress.org/plugins/meta-box/developers/) and we will update this post as soon as we have found the culprit!

**Comment by senlin** [comment]
Did some more research and it seems [the bug](https://github.com/rilwis/meta-box/issues/588) already has been reported over at the Meta Box Repo too.

The [fix](https://github.com/rilwis/meta-box/commit/295ba1ec59235c9c28c86445be092397a9396aab) offered in that post works, so you can either implement that yourself or wait until Meta Box 4.5.2 is released, which hopefully is soon...

Apologies for any inconvenience and thanks again for reporting the bug!

**Comment by digitalrub** [comment]
Thanks, Piet! I'll see if I can hack it myself

**Comment by digitalrub** [comment]
totally worked!

**Comment by senlin** [comment]
glad to hear that :)
